In the following code we are trying to pair every coordinate point (x, y, z) with a date (in Julian date)

In [1]:
#import sys
#!(sys.executable)pip install sgp4
!pip install sgp4
!pip install skyfield

In [3]:
import skyfield

if skyfield.VERSION < (1, 24):
    print('Too old')

In [4]:
from sgp4.api import Satrec
from sgp4.api import jday

In [5]:
# importing pandas as pd
import pandas as pd
import numpy as np  
# Create the Timestamp object


julian_dates = []
year_value = np.array([2010, 2011])
month_value = np.arange(1,13)

month_31days = np.array([1,3,5,7,8,10,12])
month_30days = np.array([4,6,9,11])
month_28days = np.array([2])

for year in year_value:
    for month in month_value:
        if month in month_31days:
            day_values = np.arange(1,32)
        elif month in month_30days:
            day_values = np.arange(1, 31)
        elif month in month_28days:
            day_values = np.arange(1, 29)
        for day in day_values:
            ts = pd.Timestamp(year = year,  month = month, day = day)
            julian_dates.append(ts.to_julian_date())

julian_dates = np.array(julian_dates)
print(julian_dates)

#we get the julian dates of each day between 2010/1/1 to 2011/12/31

[2455197.5 2455198.5 2455199.5 2455200.5 2455201.5 2455202.5 2455203.5
 2455204.5 2455205.5 2455206.5 2455207.5 2455208.5 2455209.5 2455210.5
 2455211.5 2455212.5 2455213.5 2455214.5 2455215.5 2455216.5 2455217.5
 2455218.5 2455219.5 2455220.5 2455221.5 2455222.5 2455223.5 2455224.5
 2455225.5 2455226.5 2455227.5 2455228.5 2455229.5 2455230.5 2455231.5
 2455232.5 2455233.5 2455234.5 2455235.5 2455236.5 2455237.5 2455238.5
 2455239.5 2455240.5 2455241.5 2455242.5 2455243.5 2455244.5 2455245.5
 2455246.5 2455247.5 2455248.5 2455249.5 2455250.5 2455251.5 2455252.5
 2455253.5 2455254.5 2455255.5 2455256.5 2455257.5 2455258.5 2455259.5
 2455260.5 2455261.5 2455262.5 2455263.5 2455264.5 2455265.5 2455266.5
 2455267.5 2455268.5 2455269.5 2455270.5 2455271.5 2455272.5 2455273.5
 2455274.5 2455275.5 2455276.5 2455277.5 2455278.5 2455279.5 2455280.5
 2455281.5 2455282.5 2455283.5 2455284.5 2455285.5 2455286.5 2455287.5
 2455288.5 2455289.5 2455290.5 2455291.5 2455292.5 2455293.5 2455294.5
 24552

In [6]:
import codecs
filename = r"TLE_data.txt"


f= open(filename, 'r')
for x in f:
    print (type(x))

#checking if all the data are strings

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class

In [14]:
t_index_list = np.arange(0,1460,2)

s_index_list = np.arange(1,1461,2)


def generate_specific_rows(filename, userows=[]):
    with open(filename) as f:
        for i, line in enumerate(f):
            if i in userows:
                yield line
a = t_index_list
gen = generate_specific_rows('TLE_data.txt', userows=a)
t_array = np.loadtxt(gen, dtype = np.str, unpack='true')
t_array = t_array.transpose()
t_array[0]

def generate_specific_rows(filename, userows=[]):
    with open(filename) as f:
        for i, line in enumerate(f):
            if i in userows:
                yield line
b = s_index_list
gen = generate_specific_rows('TLE_data.txt', userows=b)
s_array = np.loadtxt(gen, dtype = np.str, unpack='true')
s_array = s_array.transpose()
s_array[0]
print(" ".join(t_array[0]))
print(" ".join(s_array[0]))

#putting each ood row and even row in 2 different arrays

1 25467U 98051A 11365.84066151 +.00000545 +00000-0 +18753-3 0 9995
2 25467 086.3991 135.6159 0001705 075.8739 284.2652 14.34228791700764


C:\Users\franc\AppData\Local\Temp\ipykernel_18800\1414026358.py:13: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  t_array = np.loadtxt(gen, dtype = np.str, unpack='true')
C:\Users\franc\AppData\Local\Temp\ipykernel_18800\1414026358.py:24: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s_array = np.loadtxt(gen, dtype = np.str, unpack='true')


In [13]:
t_array


array([['1', '25467U', '98051A', ..., '+18753-3', '0', '9995'],
       ['1', '25467U', '98051A', ..., '18214-3', '0', '9997'],
       ['1', '25467U', '98051A', ..., '+18157-3', '0', '9998'],
       ...,
       ['1', '25467U', '98051A', ..., '10244-3', '0', '9994'],
       ['1', '25467U', '98051A', ..., '+98012-4', '0', '9992'],
       ['1', '25467U', '98051A', ..., '91209-4', '0', '9991']],
      dtype='<U14')

In [12]:
s_array

array([['2', '25467', '086.3991', ..., '075.8739', '284.2652',
        '14.34228791700764'],
       ['2', '25467', '086.3993', ..., '073.7771', '286.3628',
        '14.34228240700698'],
       ['2', '25467', '086.3990', ..., '076.5589', '283.5821',
        '14.34227626700619'],
       ...,
       ['2', '25467', '086.3955', ..., '060.2991', '299.8468',
        '14.34219058651800'],
       ['2', '25467', '086.3954', ..., '060.5992', '299.5466',
        '14.34218804651733'],
       ['2', '25467', '086.3954', ..., '059.9172', '300.2323',
        '14.34218801651720']], dtype='<U17')

In [15]:
r_array = []

for  i in range(len(julian_dates)):
    julian_date_i = julian_dates[i]
    i_t = " ".join(t_array[i])
    i_s = " ".join(s_array[i])
    satellite = Satrec.twoline2rv(i_t, i_s)

    jd, fr =julian_date_i, 0.362605
    e, r, v = satellite.sgp4(jd, fr)
    r_array.append(r)

r_array = np.array(r_array)
print(r_array)

#trying to get x, y, z positions for each TLE with the relative julian date. 
#unfortunately there are more than one TLE per each day, hence we have gap in the calculations, 
#since we have a bigger number of TLEs (about 3000) rather than days (730)
#TLEs are updated 4-6 times a day

[[-1.94363747e+06 -1.68405037e+08 -3.66814847e+08]
 [            nan             nan             nan]
 [-1.28948231e+08 -2.37387491e+08  6.98053717e+07]
 ...
 [            nan             nan             nan]
 [-1.73698591e+03  2.37086233e+03 -6.58861648e+03]
 [            nan             nan             nan]]


Unfortunately we have more TLEs per day (about 3000) than actual calendar days (730), which means that some positional datas are missing. TLEs are updated 4-6 times a day, hence we should find a code that can associate 1 TLE of each day to the Julian date of that specific day, in that case we could get 730 results (2 years time), and compare that to other satellites to get the distance between them each day of the year.